version: '3.9'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${WEBUI_PORT:-3000}:8080"  # domyślnie 3000, możesz nadpisać przez .env
    volumes:
      - ./data:/app/backend/data
      - /home/przemekp95/ai-dev-kit/embedding-models:/home/przemekp95/ai-dev-kit/embedding-models
      - "${PROJECTS_PATH:-/home/przemekp95/projekty-do-ai-dev-kit/}:/workspace/projekty"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - webui-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - "${OLLAMA_MODELS_PATH:-/home/przemekp95/.ollama}:/root/.ollama"
    restart: unless-stopped
    networks:
      - webui-net

networks:
  webui-net:
    driver: bridge
